import { memoriesIPC, type Memory } from '$lib/ipc/memories';
import { v4 as uuidv4 } from 'uuid';

export class MemoryStore {
    memories = $state<Memory[]>([]);
    loading = $state(false);
    error = $state<string | null>(null);

    async init() {
        await this.loadMemories();
    }

    async loadMemories() {
        this.loading = true;
        this.error = null;
        try {
            this.memories = await memoriesIPC.listMemories();
        } catch (err: any) {
            this.error = err.message || 'Failed to load memories';
            console.error('Error loading memories:', err);
        } finally {
            this.loading = false;
        }
    }

    async createMemory(content: string, category: string | null = null, isPinned: boolean = false, isAutoGenerated: boolean = false, sourceConversationId: string | null = null) {
        const id = uuidv4();
        try {
            await memoriesIPC.createMemory(id, content, category, isPinned, isAutoGenerated, sourceConversationId);
            await this.loadMemories();
            return id;
        } catch (err: any) {
            console.error('Error creating memory:', err);
            throw err;
        }
    }

    async updateMemory(id: string, content: string, category: string | null, isPinned: boolean) {
        try {
            await memoriesIPC.updateMemory(id, content, category, isPinned);
            await this.loadMemories();
        } catch (err: any) {
            console.error('Error updating memory:', err);
            throw err;
        }
    }

    async deleteMemory(id: string) {
        try {
            await memoriesIPC.deleteMemory(id);
            await this.loadMemories();
        } catch (err: any) {
            console.error('Error deleting memory:', err);
            throw err;
        }
    }
}

export const memoryStore = new MemoryStore();
