import { invoke } from '@tauri-apps/api/core';

export interface Memory {
    id: string;
    content: string;
    category?: string | null;
    is_pinned: boolean;
    is_auto_generated: boolean;
    source_conversation_id?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
}

export const memoriesIPC = {
    createMemory: async (id: string, content: string, category: string | null, isPinned: boolean, isAutoGenerated: boolean, sourceConversationId: string | null): Promise<void> => {
        return await invoke('create_memory', { id, content, category, isPinned, isAutoGenerated, sourceConversationId });
    },
    updateMemory: async (id: string, content: string, category: string | null, isPinned: boolean): Promise<void> => {
        return await invoke('update_memory', { id, content, category, isPinned });
    },
    deleteMemory: async (id: string): Promise<void> => {
        return await invoke('delete_memory', { id });
    },
    listMemories: async (): Promise<Memory[]> => {
        return await invoke('list_memories');
    }
};
